[package]
name = "types_prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prusti-contracts = { path = "../../../live/prusti-dev/prusti-contracts/prusti-contracts" }

[workspace]
